version: "3.5"
services:
  diva:
    image: "diva.goerli-diva.public.dappnode.eth:0.1.2"
    build:
      context: diva
      args:
        UPSTREAM_VERSION: v23.8.7
    restart: unless-stopped
    volumes:
      - "diva-vol:/opt/diva/data/"
      - "diva-log-vol:/var/log/divad/"
    environment:
      DIVA_VAULT_PASSWORD: null
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_JAEGER_AGENT_PORT: 6831
      EXECUTION_CLIENT_URL: "ws://goerli-geth.dappnode:8546"
      CONSENSUS_CLIENT_URL: "http://beacon-chain.prysm-prater.dappnode:3500"
      DIVA_API_KEY: null
    ports:
      - "5050:5050"
      - "30000:30000"
    expose:
      - "9000"
  validator:
    image: "validator.goerli-diva.public.dappnode.eth:0.1.2"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v4.0.7
    restart: unless-stopped
    volumes:
      - "validator-config-vol:/config"
      - "validator-data-vol:/data"
      - "validator-jwt-vol:/jwt"
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.prysm-prater.dappnode:4000"
    expose:
      - "7500"
  reloader:
    image: "reloader.goerli-diva.public.dappnode.eth:0.1.2"
    build:
      context: reloader
      args:
        UPSTREAM_VERSION: v23.8.0
    restart: unless-stopped
    volumes:
      - "validator-jwt-vol:/jwt"
    environment:
      VALIDATOR_RKM_API: "http://validator.goerli-diva.public.dappnode:7500"
      DIVA_W3S_API: "http://diva.goerli-diva.public.dappnode:9000"
      SYNC_PERIOD: 600
  ui:
    image: "ui.goerli-diva.public.dappnode.eth:0.1.2"
    build:
      context: operator-ui
      args:
        UPSTREAM_VERSION: v23.8.2
    restart: unless-stopped
    ports:
      - "8888:80"
  jaeger:
    image: "jaeger.goerli-diva.public.dappnode.eth:0.1.2"
    build:
      context: jaeger
      args:
        UPSTREAM_VERSION: v23.8.0
    restart: unless-stopped
  vector:
    image: "vector.goerli-diva.public.dappnode.eth:0.1.2"
    build:
      context: vector
      args:
        UPSTREAM_VERSION: v23.8.0
    restart: unless-stopped
    volumes:
      - "diva-log-vol:/var/log/divad/"
    environment:
      USERNAME: username-address
volumes:
  diva-vol: {}
  diva-log-vol: {}
  validator-config-vol: {}
  validator-data-vol: {}
  validator-jwt-vol: {}
